#!/usr/bin/env bash

_android_arm32_fix() {
  local \
    _arch \
    _file \
    _file_name \
    _pkgs
  _arch="$(
    uname \
      -m)"
  _pkgs="$(
  find \
    "${PWD}" \
    -iname \
      "*.pkg.tar.xz")"
  for _file in ${_pkgs}; do \
    echo \
      "file: ${_file}"; \
    _file_name="${_file%*-armv8l.pkg.tar.xz}"
    echo \
      "file: ${_file}"
    if [[ "${_arch}" == "armv8l" ]]; then \
      mv \
        "${_file}" \
        "${_file_name}-arm.pkg.tar.xz" || \
      true
      mv \
        "${_file}.sig" \
        "${_file_name}-arm.pkg.tar.xz.sig" || \
      true
    fi
  done
}

_android_arm32_fix
